### ISSUE TITLE
Needs to be a standalone repo for GitHub credit

### ISSUE THREAD

**Issue by hopeseekr** [FakerPHP/Faker#36] opened 2020-10-30 05:24 UTC
## The Problem

This is a standalone repository. Therefore, anyone who contributes to it will not get any GitHub credit, like https://github.com/username Activity.

## The Solution

Esp since the original is abandoned, simply delete this repo, create a blank one, and do `git push --tags origin master`.

**Comment by Nyholm** [comment] 2020-10-30 07:49
Hey. Thank you for this issue. 

I don't contribute to open source to make sure my Github dashboard is full with credits. I do it because I like to help other people to solve problems. 
But I understand that this is important to some people. If I look at a recent contributors dashboard, I'll see that their activity do show up in their dashboard.

<img width="811" alt="Screenshot 2020-10-30 at 08 45 50" src="https://user-images.githubusercontent.com/1275206/97673746-93106180-1a8c-11eb-966c-b0a1ec374740.png">

I dont see the need to removing the label that says that this is a fork. That label is actually a good thing. It shows people that we didnt rebuild this from scratch. 

Im closing this issue since the problem is not reproducible and the solution is not preferred.

**Closed by Nyholm** 2020-10-30 07:49 UTC
