### ISSUE TITLE
$this->faker->image() always returns false

### ISSUE THREAD

**Issue by sajendramanandhar** [FakerPHP/Faker#488] opened 2022-07-01 06:25 UTC
### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.1.7   |
| `fakerphp/faker`  | 1.19.0   |

### Self-enclosed code snippet for reproduction

```php
$this->faker->image('public/storage/')
```

### Expected output

```txt
should have generated a fake image
```

### Actual output
when dump and die the result, false is returned.
```txt
false
```

**Comment by bram-pkg** [comment] 2022-07-01 06:35
Duplicate of #475

**Closed by bram-pkg** 2022-07-01 06:35 UTC
