### ISSUE TITLE
`Base::unique` contains null while type says it does not

### ISSUE THREAD

**Issue by simPod** [FakerPHP/Faker#313] opened 2021-04-27 20:56 UTC
### Summary

`Base::unique` property is not initialized in constructor and its type does not allow `null` value. 

Though, the `null` value is there so the type is wrong and it's a bug.

### Versions

|                | Version |
|:---------------|:--------|
| `fakerphp/faker`  | 1.y.z   |

### Self-enclosed code snippet for reproduction

See https://github.com/FakerPHP/Faker/pull/309 on how to fix the bug

**Comment by pimjansen** [comment] 2021-04-28 06:00
What is the codesnippet to reproduce behaviour that is not expected.

It is not initialized which means initially it is null?

**Comment by simPod** [comment] 2021-04-28 07:54
> It is not initialized which means initially it is null?

Yes, how could it be something else?

```php
final class Ooof extends Base
{
    public function readUnique() : UniqueGenerator
    {
        return $this->unique;
    }
}


$ooof = new Ooof(new Generator());
$ooof->readUnique(); // 🎶
```

**Comment by simPod** [comment] 2021-05-12 10:34
activity

**Comment by simPod** [comment] 2021-05-27 21:24
6

**Comment by bramceulemans** [comment] 2021-05-27 22:11
> > It is not initialized which means initially it is null?
> 
> Yes, how could it be something else?
> 
> ```
> final class Ooof extends Base
> {
>     public function readUnique() : UniqueGenerator
>     {
>         return $this->unique;
>     }
> }
> 
> 
> $ooof = new Ooof(new Generator());
> $ooof->readUnique(); // 🎶
> ```

Is the the full code snippet, @simPod ?

**Comment by simPod** [comment] 2021-05-30 09:17
@bramceulemans yes I guess? What are you asking exactly?

**Comment by bramceulemans** [comment] 2021-05-30 09:20
Where is your constructor, your field assignment to `$this->unique`?

**Comment by simPod** [comment] 2021-05-30 09:22
Those are your classes as stated in the issue summary

```php
use Faker\Generator;
use Faker\Provider\Base;
use Faker\UniqueGenerator;

final class Ooof extends Base
{
    public function readUnique() : UniqueGenerator
    {
        return $this->unique;
    }
}

$ooof = new Ooof(new Generator());
$ooof->readUnique(); // 🎶
```

**Comment by bramceulemans** [comment] 2021-06-09 16:49
You are missing the constructor in your `Ooof` class, or am I misunderstanding you?

**Comment by simPod** [comment] 2021-06-10 00:02
If there's missing constructor, `Base` is the one missing it.

Either the `unique` property should be nullable or should be set some default value in `Base`.

**Comment by pimjansen** [comment] 2021-06-13 11:32
I do not think we can do an easy fix here without it being a breaking change.

Since we have a 2.x roadmap we can not just push these breaking changes (since this class is not final).

So i think we should live with it for now

**Comment by simPod** [comment] 2021-06-13 17:22
I've created the issue to track the bug so others that encounter it as well can subscribe. You've closed my PR that fixes it already. So the version&roadmap this should be fixed in is your decision ofc.

**Comment by pimjansen** [comment] 2021-06-13 18:02
> I've created the issue to track the bug so others who encounter it as well can subscribe. You've closed my PR that fixes it already. So the version&roadmap this should be fixed in is your decision ofc.

Yeah that is fine. In the future these will be final so we can control it a bit better

**Comment by bramceulemans** [comment] 2021-06-13 18:22
I'm not sure that changing a phpdoc block would cause any breaking changes?

**Comment by pimjansen** [comment] 2021-06-13 19:18
> I'm not sure that changing a phpdoc block would cause any breaking changes?

It will not but initialising it as null will. At this point it has no value.

The main issue is that it can cause an error that the value is used before initialising.

**Comment by simPod** [comment] 2021-06-27 20:16
387

**Comment by pimjansen** [comment] 2021-07-06 20:44
I am closing this since this can not be fixed without a breaking change we do not allow at this point (see contribution guide). For Faker 2.x we will take this into account. Probably those classes will be final to start with so that this can not be extended and only decorated or something like that.

**Closed by pimjansen** 2021-07-06 20:44 UTC
